version: "3.8"
services:
  my-mongo-db:
    container_name: mongodb
    image: mongo:4.4.3
    ports:
      - "27017:27017"
    volumes:
      - misdatosmongo:/data/db
  mongo-gui:
    container_name: "mongo-gui"
    image: ugleiton/mongo-gui
    restart: always
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://localhost:27017
volumes:
  misdatosmongo:
